services:
  - type: web
    name: paella-giobel
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node app.js
    envVars:
      - key: NODE_ENV
        value: production